[package]
name = "yanyan"
version = "0.3.0"
description = "砚砚 - AI 小说写作助手"
authors = ["HraySet"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.11.2", features = [] }
tauri-plugin-dialog = "2"
time = { version = "0.3", features = ["formatting", "macros"] }
